image: rocker/tidyverse:latest

stages:
  - test

Comparison:
  stage: test
  script:
    - |
      R -e '
        install.packages("opalr", repos = "http://cran.rstudio.com/")
        install.packages("diffdf", repos = "http://cran.rstudio.com/")
      '

    - |
      R -e '
        ## Read in initializations
        source("CI_CD/CICD_procedure.R")

        ## Run the tests
        source("CI_CD/CICD_check.R")

        ## Check if there is an mismatch
        load(fakedata_CICD_diffs.Rdata)
        if(length(fakedata_CICD_diffs) > 1){error("There are mismatches")}
      '
  artifacts:
    paths:
      - fakedata_CICD_diffs.Rdata
    when: always
