
default:
  image: rocker/tidyverse:4.5.1

stages:
  - build
  - tables

Build:
  stage: build
  script:
    - R CMD build .
    - PKG_FILE=$(ls *.tar.gz)
    - Rscript ./cicd/install_packages.R
    - R CMD INSTALL "$PKG_FILE"

Tables:
  stage: tables
  script:
    - Rscript ./cicd/run_step_tables.R
