
default:
  image: rocker/tidyverse:4.5.1

stages:
  - build
  - tables

Build:
  stage: build
  script:
    - R CMD build .
    - PKG_FILE=$(ls *.tar.gz)
    - Rscript ./cicd/packages/install_packages.R
    - R CMD INSTALL "$PKG_FILE"

Tables:
  stage: tables
  before_script:
    - R CMD build .
    - PKG_FILE=$(ls *.tar.gz)
    - Rscript ./cicd/packages/install_packages.R
    - R CMD INSTALL "$PKG_FILE"
  script:
    - Rscript ./cicd/01_tables/adm.table_get.R
    - Rscript ./cicd/01_tables/adm.table_save_write.R
    - Rscript ./cicd/01_tables/adm.table_save_update.R
    - Rscript ./cicd/01_tables/adm.table_save_overwrite.R
    - (! Rscript ./cicd/01_tables/adm.table_save_overwrite.R)
  after_script:
    - Rscript ./cicd/01_tables/cleanup.R
